# Generated by Django 5.0.7 on 2024-07-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0, verbose_name='age'),
            preserve_default=False,
        ),
    ]
